sudo: required
language: generic 

services:
    - docker
before_install:
    - docker build -t onlyrahul4u/frontenddocker -f Dockerfile.dev .

script:
    - docker run -e CI=true onlyrahul4u/frontenddocker npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "frontenddocker"
    env: "Frontenddocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-095504243037"
    bucket_path: "frontenddocker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


    
    